select productId, productBarCode,productName,productCompanyName,productPurpose productDescription,productCategory,
productLocation,productExpridate,productBatch,productColor1,productColor2,productColor3
 productSize,productUnits,productQuantityPack,productQntHand,productTotalPack,productTotalPeice
 productMinStock,productMaxStock,productSalePrice,ProductPurchasePrice,ProductProfit,
 ProductMaxDiscount,productTotalProfit,productItemDiscount
productDistributors,productUpdateStock,productInactive,updateDate from addNewProducts